### ISSUE TITLE
About the date that the code will be released

### ISSUE THREAD

**Issue by Zwette** [IGITUGraz/WeatherDiffusion#1]
Thanks for your impressive work which is inspiring. I would like to ask when the code will be released.

Many thanks again!

**Comment by oozdenizci** [comment]
Thanks a lot! The working code repository needs to be cleaned up, and it's particularly a busy time nowadays. 
Targeted date is (latest) August 20th, so please check back later until then.
Thanks for your understanding!

**Comment by Zwette** [comment]
Grateful for your contribution!
