### ISSUE TITLE
How to prepare the test dataset

### ISSUE THREAD

**Issue by oubotong** [IGITUGraz/WeatherDiffusion#10]
I was trying to test the model but there lacks information about how to set up the test dataset. (especially the `allweather.txt` and `raindroptesta.txt` file).

Could you please add some instructions on how to set it up. Thanks!

**Comment by oozdenizci** [comment]
Please refer to the [TransWeather](https://github.com/jeya-maria-jose/TransWeather) Github repository for test set benchmarks (it includes the same .txt files used here as well). Our evaluations and comparisons were mainly based on those.

**Comment by oubotong** [comment]
> Please refer to the [TransWeather](https://github.com/jeya-maria-jose/TransWeather) Github repository for test set benchmarks (it includes the same .txt files used here as well). Our evaluations and comparisons were mainly based on those.

Thanks!

**Comment by henlyta** [comment]
PermissionError: [Errno 13] Permission denied: 'datasets/'   The code keeps reporting this error, may I ask what is the problem?

**Comment by Depoul** [comment]
Hi @oubotong! did you resolve the issue? By setting up the TransWeather repo and dataset, i only managed to resolve the allweather.txt missin error. When it comes to raindroptesta.txt, of course, it gives me an error. Do you have any suggestions?
