### ISSUE TITLE
Could you provide train bash?

### ISSUE THREAD

**Issue by Catherine981234** [IGITUGraz/WeatherDiffusion#11]
Thank you for your wonderful work.Could you provide train bash or correct my bash? I find some color differences when I use your code to train other images.Thus, I want to check if this is something wrong with train bash.

my train bash:
CUDA_VISIBLE_DEVICES=1,2  python train_diffusion.py --config "allweather.yml" --image_folder='results/all_weather'

**Comment by oozdenizci** [comment]
Thanks! The train bash would exactly be as you indicate here. The config file 'allweather.yml' should in this case be of course modified according to your input images' directory etc.

What kind of color differences? Early during training, generated patch samples collected in the image_folder might have significant contrast differences of course, which is normal. This should vanish later during training.
