### ISSUE TITLE
Can you provide the WeatherDiff128 model weights?

### ISSUE THREAD

**Issue by RoyMikeJiang** [IGITUGraz/WeatherDiffusion#12]
Thanks for your interesting and amazing work. I wanna to compare the results of two different imagesize network and use them as the pre-trained weights. But I only find the WeatherDiff64 model weights in the readme. So can you provide the WeatherDiff128 model weights? Thank you!

**Comment by oozdenizci** [comment]
Thanks for your request! I just updated the readme with a link to the WeatherDiff128 model, and the config associated with it in the configs folder.
