### ISSUE TITLE
about the source code

### ISSUE THREAD

**Issue by fei1998** [IGITUGraz/WeatherDiffusion#2]
Thank you so much for your awesome work! I would like to ask when the code will be released.
Best wishes.

**Comment by oozdenizci** [comment]
Thanks a lot! The working code repository needs to be cleaned up, and it's particularly a busy time nowadays. 
Targeted date is (latest) August 20th, so please check back later until then.
Thanks for your understanding!

**Comment by fei1998** [comment]
Thanks a lot!
Best wishes.
