### ISSUE TITLE
Could you provide some checkpoints?

### ISSUE THREAD

**Issue by anonymw** [IGITUGraz/WeatherDiffusion#4]
Thank you for your amazing work. I noticed that you trained all models for about 2, 000, 000 iterations. It may takes too much time to train the model from scratch. So can you release some checkpoints or provide some training details such as hardware and training time?

**Comment by oozdenizci** [comment]
Apologies for the delay. I just added a link to a pre-trained model checkpoint for the multi-weather restoration network. Thanks for your patience!
