### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by tonia86** [IGITUGraz/WeatherDiffusion#7]
Thanks for your interesting work! I would like to know, how long does it take to train WeatherDiff64？

**Comment by oozdenizci** [comment]
We have included some information regarding this in our paper supplementary (which will be available soon). For us, WeatherDiff64 model training for 2M iterations took ~15 days on 4 NVIDIA-A40 GPUs.

FYI - I have just added a pre-trained model checkpoint link to the repository, which should be sufficient for fast evaluations if needed.

**Comment by tonia86** [comment]
That's great, thanks for your reply！
