### ISSUE TITLE
About Dataset（Test1 of Outdoor-Rain)

### ISSUE THREAD

**Issue by cecret3350** [IGITUGraz/WeatherDiffusion#9]
Hi @oozdenizci  , thanks for your amazing work!

I would like to ask where I can find the test set Test1 corresponding to Outdoor-Rain, because I did not find the test set in the official github of [Outdoor-Rain](https://github.com/liruoteng/HeavyRainRemoval). 

Looking forward to your reply!

**Comment by oozdenizci** [comment]
Thank you for your interest! This test dataset was previously retrieved from the [TransWeather](https://github.com/jeya-maria-jose/TransWeather) repository for direct comparisons, as well as the other training/test sets. I believe a link to the Test1 set should be still there (if not, please check earlier commits).

**Comment by cecret3350** [comment]
> Thank you for your interest! This test dataset was previously retrieved from the [TransWeather](https://github.com/jeya-maria-jose/TransWeather) repository for direct comparisons, as well as the other training/test sets. I believe a link to the Test1 set should be still there (if not, please check earlier commits).

Thank you very much! Your answer solved my problem!
